#!/bin/bash
#PBS -q development
#PBS -N Liweihao
#PBS -V
#PBS -l select=1:ncpus=8
# change to the working directory 
cd $PBS_O_WORKDIR

echo ">>>> Begin  scrub"

# actual binary (with IO redirections) and required input 
# parameters is called in the next line
module load python/2.7.12_anaconda
mpirun -np 8 python /scratch/li.weihao/2017-MATH-9898-Li-Weihao/Assignment_01/SCRUB.py data.txt > output.txt 2>&1

echo "ALL DONE""
